// Feature 16.2 — Local Android Shell Proof.
//
// This is a PACKAGING PROOF, not a customer-ready Android POS. The shell is
// a Capacitor WebView that loads the already-deployed/hosted POS Canvas
// runtime over the network. It bundles no POS runtime, no configuration, and
// no credentials of any kind.
//
// What this configuration deliberately does NOT contain, per the approved
// Milestone 16 architecture:
//   - no service-role key, no anon key, no Supabase credentials at all
//     (the hosted page supplies its own NEXT_PUBLIC_* values to the browser)
//   - no customer id, project id, or build-job id
//   - no embedded GeneratedPosConfig
//   - no finalized production package identity
//   - no signing configuration
//
// Authentication in this feature is still the owner's own web session,
// inherited from the hosted runtime. That is acceptable ONLY as a developer
// proof: a real till needs the device pairing introduced in Feature 16.3.
import type { CapacitorConfig } from "@capacitor/cli";
import { readAndroidServerUrl } from "./android-shell/serverUrl.mjs";

// Throws with actionable guidance when POS_CANVAS_ANDROID_SERVER_URL is
// missing or malformed, so any cap command fails loudly rather than
// silently producing a shell pointed at nothing (or at a stale default).
const { url, isCleartext, isRelease } = readAndroidServerUrl();

const config: CapacitorConfig = {
  // Feature 20 — the FINAL production application id, replacing the
  // provisional com.poscanvas.dev.
  //
  // This value is permanent. An Android app is identified by its
  // applicationId together with its signing certificate: once a customer has
  // installed a signed build, changing either one means Android sees a
  // different app, with no upgrade path and no way to carry a paired session
  // across. It must stay in lockstep with `namespace`/`applicationId` in
  // android/app/build.gradle and with the MainActivity package declaration.
  appId: "com.poscanvas.app",

  appName: "POS Canvas",

  // Feature 16.2 — generated by android-shell/generateWww.mjs. In this
  // feature these local files are NOT the POS runtime: index.html is only
  // reachable if server.url below is removed, and offline.html is the
  // honest failure screen referenced by server.errorPath.
  webDir: "android-shell/www",

  server: {
    // The hosted POS Canvas runtime. Configurable per machine; never
    // hardcoded and never committed.
    url,

    // Feature 16.2 — shown when the hosted runtime cannot be reached, so a
    // no-network device gets an honest message instead of an indefinite
    // white screen. This shell has no offline capability and the page says
    // so plainly.
    errorPath: "offline.html",

    // Feature 16.2 — cleartext is enabled ONLY when the configured URL is
    // http, i.e. a local dev server with no TLS. Capacitor's own type docs
    // state plainly that this "is not intended for use in production", and
    // it is treated that way here: an https URL leaves it false, and the
    // generated Android network-security config is narrowed by hand to the
    // single dev host (see android/app/src/main/res/xml/) rather than left
    // permitting cleartext to anywhere.
    //
    // `server.hostname` is deliberately NOT set from the URL: despite the
    // name it configures the WebView's *local* scheme hostname (default
    // "localhost"), not an allowlist for the remote origin. Pointing it at
    // a dev host would be incorrect and would risk losing secure-context
    // Web APIs.
    ...(isCleartext ? { cleartext: true } : {}),
  },

  android: {
    // Feature 16.2 — keeps the WebView's own scroll/bounce behavior
    // predictable inside the app shell. No kiosk mode, no lock task mode,
    // and no irreversible hiding of system navigation: this is a normal,
    // exitable app, exactly as scoped.
    allowMixedContent: false,

    // Feature 20 — remote WebView debugging, ON for development and OFF for
    // release.
    //
    // This was previously unconditional. On a released till it would expose the
    // full contents of a live POS session — including the paired device's
    // stored auth session — to anyone who can reach the device over adb. It is
    // now tied to the same explicit release flag that pins the production URL,
    // so the two cannot disagree about which kind of build this is.
    webContentsDebuggingEnabled: !isRelease,
  },
};

export default config;
