import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Feature 16.2 — the generated native Android project. Everything under
    // android/ is either Capacitor-generated scaffolding, a Gradle build
    // intermediate, or third-party vendored JS (e.g.
    // android/app/build/.../native-bridge.js, which this project does not
    // author and cannot meaningfully fix). Capacitor's own
    // android/.gitignore already keeps the build outputs out of git, but
    // ESLint does not read nested .gitignore files, so without this the
    // suite reports warnings for generated code.
    "android/**",
    // Generated by android-shell/generateWww.mjs on every android:sync.
    "android-shell/www/**",
  ]),
]);

export default eslintConfig;
