import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { BRAND, BRAND_TAGLINE } from "@/lib/brand";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Feature 24.1 — the site's own identity, from the shared brand module.
//
// This was still the create-next-app default ("Create Next App", "Generated by
// create next app"), which is what every owner saw in their browser tab and
// what any link preview would have shown. It is the root layout, so it covers
// the landing page, the dashboard and the editor.
//
// `title.template` gives every route a consistent suffix while letting a route
// name itself — /device already sets "POS Canvas — Device", and that keeps
// working because `default` only applies where a page sets nothing.
export const metadata: Metadata = {
  title: {
    default: BRAND.productName,
    template: `%s · ${BRAND.productName}`,
  },
  description: BRAND_TAGLINE,
  applicationName: BRAND.productName,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
