// Feature 24.5C — the queue's public API: storage I/O plus the pure rules.
//
// Thin by design, like lib/deviceOfflineSession.ts. Every rule lives in
// lib/saleQueue.ts and every byte of I/O in lib/deviceOfflineStore.ts; this
// module owns the small amount of glue between them, so there is no third place
// for a rule to hide.
//
// NOTHING HERE TALKS TO THE NETWORK. 24.5C persists sale intents and nothing
// else — no submission, no retry loop, no complete_sale_v4 call. 24.5D adds
// that on top of this floor. The offline checkout fence from 24.5A is untouched
// and nothing in the app calls enqueueSale yet.
//
// SECURITY, stated once: a queued record holds item ids, quantities, modifier
// selections, a "cash"/"card" LABEL and timestamps. It holds no card number, no
// CVV, no expiry, no cardholder name and no track data — POS Canvas never
// receives any of those, so there is nothing to store. It holds no Supabase
// key, no service-role credential and no session token; the device's auth
// session stays where it already was, in the Supabase client's own storage.
// lib/offlineQueue.guards.test.ts asserts every one of those.
import {
  SALE_QUEUE_SCHEMA_VERSION,
  SALE_REQUEST_PAYLOAD_VERSION,
  beginOperatorRetry,
  isDueForAttempt,
  isManuallyRetryable,
  markQueuedSaleAttempt,
  readQueuedSale,
  recoverInterruptedSale,
  sortQueueFifo,
  summarizeQueue,
  transitionQueuedSale,
} from "@/lib/saleQueue";
import type {
  QueueReadFailure,
  QueueState,
  QueueSummary,
  QueuedSale,
  QueuedSaleItem,
} from "@/lib/saleQueue";
import {
  countQueuedSaleRecords,
  deleteQueuedSaleRecord,
  insertQueuedSale,
  openOfflineDb,
  putQueuedSale,
  readAllQueuedSaleRecords,
  readQueuedSaleByRequestId,
  readQueuedSaleRecord,
} from "@/lib/deviceOfflineStore";
import type { PaymentMethod } from "@/lib/cart";

export type QueueFailure =
  | "storage_unavailable"
  | "write_failed"
  | "duplicate_sale_request"
  | "not_found"
  | "corrupt_record"
  | "illegal_transition";

export type QueueResult<T> = { ok: true; value: T } | { ok: false; reason: QueueFailure };

/** A record that failed validation on read, kept visible rather than dropped. */
export type QuarantinedSale = { queueRecordId: string | null; reason: QueueReadFailure };

async function withDb<T>(
  run: (db: IDBDatabase) => Promise<QueueResult<T>>
): Promise<QueueResult<T>> {
  const opened = await openOfflineDb();

  if (!opened.ok) {
    return { ok: false, reason: "storage_unavailable" };
  }

  try {
    return await run(opened.value);
  } finally {
    opened.value.close();
  }
}

// ---------------------------------------------------------------------------
// Enqueue
// ---------------------------------------------------------------------------

export type EnqueueSaleInput = {
  /** Generated by the CALLER, before this function is reached. See below. */
  saleRequestId: string;
  queueRecordId: string;
  deviceAuthUserId: string;
  deviceId: string;
  projectId: string;
  buildJobId: string;
  paymentMethod: PaymentMethod;
  items: QueuedSaleItem[];
  occurredAt: string;
  now: string;
};

/**
 * Persists a sale intent. The ONLY way a record enters the queue.
 *
 * THE IDEMPOTENCY KEY IS AN INPUT, NOT SOMETHING THIS FUNCTION MINTS. That is
 * the whole point of 24.5C: the caller generates the saleRequestId, and this
 * function makes it durable in the same transaction as the record. Once this
 * returns ok, the key exists on disk and every future retry — after a reload,
 * an app restart, a process kill — reuses it. A function that generated its own
 * key would produce a new one each time it was called, which is exactly how a
 * crash-and-retry becomes two sales.
 *
 * ENQUEUE IS ALL-OR-NOTHING. `add` (not `put`) plus the unique index on
 * saleRequestId means the storage engine itself refuses a second record for one
 * sale. A failure returns a clear reason and the caller must treat the sale as
 * NOT queued — there is no partial success, and no in-memory or localStorage
 * fallback for a financial record.
 */
export async function enqueueSale(input: EnqueueSaleInput): Promise<QueueResult<QueuedSale>> {
  const record: QueuedSale = {
    queueSchemaVersion: SALE_QUEUE_SCHEMA_VERSION,
    requestPayloadVersion: SALE_REQUEST_PAYLOAD_VERSION,
    queueRecordId: input.queueRecordId,
    saleRequestId: input.saleRequestId,
    deviceAuthUserId: input.deviceAuthUserId,
    deviceId: input.deviceId,
    projectId: input.projectId,
    buildJobId: input.buildJobId,
    paymentMethod: input.paymentMethod,
    // Devices may not tip. complete_sale_v4 rejects a non-zero device tip, so a
    // record carrying one could never be submitted.
    tipAmount: 0,
    items: input.items,
    occurredAt: input.occurredAt,
    source: "offline_queued",
    state: "pending",
    queuedAt: input.now,
    updatedAt: input.now,
    attemptCount: 0,
    lastAttemptAt: null,
    nextAttemptAt: null,
    lastErrorCode: null,
    lastErrorMessage: null,
    serverOrderId: null,
    serverOrderNumber: null,
    serverCreatedAt: null,
  };

  // Validated BEFORE it is written, using the same reader that guards every
  // load. A record that could not be read back is a record that must not be
  // written: it would sit in the queue forever, unsubmittable.
  const validated = readQueuedSale(record);

  if (!validated.ok) {
    return { ok: false, reason: "corrupt_record" };
  }

  return withDb(async (db) => {
    const existing = await readQueuedSaleByRequestId(db, input.saleRequestId);

    if (existing.ok && existing.value !== null) {
      return { ok: false, reason: "duplicate_sale_request" };
    }

    const written = await insertQueuedSale(db, validated.record);

    // The unique index is the authority here; this pre-check is a courtesy that
    // produces a better reason code. A constraint violation reaching this point
    // still means the same thing: the sale is already queued.
    if (!written.ok) {
      return { ok: false, reason: "duplicate_sale_request" };
    }

    return { ok: true, value: validated.record };
  });
}

// ---------------------------------------------------------------------------
// Reads
// ---------------------------------------------------------------------------

export async function getQueuedSale(queueRecordId: string): Promise<QueueResult<QueuedSale>> {
  return withDb(async (db) => {
    const raw = await readQueuedSaleRecord(db, queueRecordId);

    if (!raw.ok) return { ok: false, reason: "storage_unavailable" };
    if (raw.value === null) return { ok: false, reason: "not_found" };

    const parsed = readQueuedSale(raw.value);

    return parsed.ok
      ? { ok: true, value: parsed.record }
      : { ok: false, reason: "corrupt_record" };
  });
}

export async function getSaleByRequestId(
  saleRequestId: string
): Promise<QueueResult<QueuedSale>> {
  return withDb(async (db) => {
    const raw = await readQueuedSaleByRequestId(db, saleRequestId);

    if (!raw.ok) return { ok: false, reason: "storage_unavailable" };
    if (raw.value === null) return { ok: false, reason: "not_found" };

    const parsed = readQueuedSale(raw.value);

    return parsed.ok
      ? { ok: true, value: parsed.record }
      : { ok: false, reason: "corrupt_record" };
  });
}

export type QueueListing = {
  sales: QueuedSale[];
  /** Records that failed validation. Never silently dropped — see below. */
  quarantined: QuarantinedSale[];
};

/**
 * Every queued sale, FIFO, with unreadable records reported alongside.
 *
 * A corrupt record is NOT skipped quietly. It is money someone took, and the
 * only honest thing a reader can do is say "there is a row here I cannot
 * understand". 24.5D turns each of these into a needs_attention item for the
 * owner rather than deleting it.
 */
export async function listQueuedSales(): Promise<QueueResult<QueueListing>> {
  return withDb(async (db) => {
    const raw = await readAllQueuedSaleRecords(db);

    if (!raw.ok) return { ok: false, reason: "storage_unavailable" };

    const sales: QueuedSale[] = [];
    const quarantined: QuarantinedSale[] = [];

    for (const entry of raw.value) {
      const parsed = readQueuedSale(entry);

      if (parsed.ok) {
        sales.push(parsed.record);
        continue;
      }

      const id =
        entry !== null && typeof entry === "object" && !Array.isArray(entry)
          ? ((entry as Record<string, unknown>).queueRecordId as string | undefined) ?? null
          : null;

      quarantined.push({ queueRecordId: id, reason: parsed.reason });
    }

    return { ok: true, value: { sales: sortQueueFifo(sales), quarantined } };
  });
}

/** The FIFO work list a sync engine will drain. */
export async function listPendingSales(): Promise<QueueResult<QueuedSale[]>> {
  const listing = await listQueuedSales();

  return listing.ok
    ? { ok: true, value: listing.value.sales.filter((sale) => sale.state === "pending") }
    : listing;
}

/**
 * Feature 24.5D — pending sales whose backoff window has elapsed, FIFO.
 *
 * A record still inside its window is skipped, not reordered: it keeps its
 * place in the queue and simply is not eligible yet. That is what lets one
 * failing sale back off without holding up the sales behind it.
 */
export async function listDueSales(
  now: number,
  /**
   * Feature 24.5F — a manual press may skip a pending backoff, and nothing else
   * may. Defaults to false so every automatic caller keeps the old behaviour
   * without knowing this parameter exists.
   */
  options: { ignoreBackoff?: boolean } = {}
): Promise<QueueResult<QueuedSale[]>> {
  const listing = await listQueuedSales();
  const due = options.ignoreBackoff === true
    ? (sale: QueuedSale) => isManuallyRetryable(sale)
    : (sale: QueuedSale) => isDueForAttempt(sale, now);

  return listing.ok ? { ok: true, value: listing.value.sales.filter(due) } : listing;
}

/**
 * Feature 24.5D — records the server's identity for a synced sale.
 *
 * The state change and the order identity are written TOGETHER, so a record can
 * never be `synced` without the order number that proves it. Retry metadata is
 * normalised at the same time: there is nothing left to retry.
 */
export async function markSynced(
  queueRecordId: string,
  receipt: { orderId: string; orderNumber: string; createdAt: string | null },
  now: string
): Promise<QueueResult<QueuedSale>> {
  return withDb(async (db) => {
    const raw = await readQueuedSaleRecord(db, queueRecordId);

    if (!raw.ok) return { ok: false, reason: "storage_unavailable" };
    if (raw.value === null) return { ok: false, reason: "not_found" };

    const parsed = readQueuedSale(raw.value);

    if (!parsed.ok) return { ok: false, reason: "corrupt_record" };

    const moved = transitionQueuedSale(parsed.record, "synced", now);

    if (!moved.ok) return { ok: false, reason: "illegal_transition" };

    const synced: QueuedSale = {
      ...moved.record,
      serverOrderId: receipt.orderId,
      serverOrderNumber: receipt.orderNumber,
      serverCreatedAt: receipt.createdAt,
      nextAttemptAt: null,
      lastErrorCode: null,
      lastErrorMessage: null,
    };

    const written = await putQueuedSale(db, synced);

    return written.ok ? { ok: true, value: synced } : { ok: false, reason: "write_failed" };
  });
}

export async function getQueueSummary(): Promise<QueueResult<QueueSummary>> {
  const listing = await listQueuedSales();

  return listing.ok ? { ok: true, value: summarizeQueue(listing.value.sales) } : listing;
}

/** Raw row count, including anything quarantined. Cheap; no validation. */
export async function countQueuedSales(): Promise<QueueResult<number>> {
  return withDb(async (db) => {
    const counted = await countQueuedSaleRecords(db);

    return counted.ok
      ? { ok: true, value: counted.value }
      : { ok: false, reason: "storage_unavailable" };
  });
}

// ---------------------------------------------------------------------------
// Mutations
// ---------------------------------------------------------------------------

/** Moves one record through the state machine, refusing illegal transitions. */
export async function updateQueueState(
  queueRecordId: string,
  to: QueueState,
  now: string,
  patch: Partial<Pick<QueuedSale, "lastErrorCode" | "lastErrorMessage" | "nextAttemptAt">> = {}
): Promise<QueueResult<QueuedSale>> {
  return withDb(async (db) => {
    const raw = await readQueuedSaleRecord(db, queueRecordId);

    if (!raw.ok) return { ok: false, reason: "storage_unavailable" };
    if (raw.value === null) return { ok: false, reason: "not_found" };

    const parsed = readQueuedSale(raw.value);

    if (!parsed.ok) return { ok: false, reason: "corrupt_record" };

    const moved = transitionQueuedSale(parsed.record, to, now, patch);

    if (!moved.ok) return { ok: false, reason: "illegal_transition" };

    const written = await putQueuedSale(db, moved.record);

    return written.ok ? { ok: true, value: moved.record } : { ok: false, reason: "write_failed" };
  });
}

/** Increments the attempt counter. Kept separate so a transition cannot reset it. */
/**
 * Feature 24.5F — applies beginOperatorRetry to a stored record.
 *
 * Goes through the same read-parse-transition-write shape updateQueueState uses,
 * rather than exposing raw storage to a caller: the transition is still checked,
 * a corrupt record is still refused, and there is still exactly one module that
 * writes the queue. updateQueueState itself cannot serve here because its patch
 * deliberately covers only the error metadata, and this must also reset the
 * attempt counter.
 */
export async function startOperatorRetry(
  queueRecordId: string,
  now: string
): Promise<QueueResult<QueuedSale>> {
  return withDb(async (db) => {
    const raw = await readQueuedSaleRecord(db, queueRecordId);

    if (!raw.ok) return { ok: false, reason: "storage_unavailable" };
    if (raw.value === null) return { ok: false, reason: "not_found" };

    const parsed = readQueuedSale(raw.value);

    if (!parsed.ok) return { ok: false, reason: "corrupt_record" };

    const moved = beginOperatorRetry(parsed.record, now);

    if (!moved.ok) return { ok: false, reason: "illegal_transition" };

    const written = await putQueuedSale(db, moved.record);

    return written.ok ? { ok: true, value: moved.record } : { ok: false, reason: "write_failed" };
  });
}

export async function markAttempt(
  queueRecordId: string,
  now: string
): Promise<QueueResult<QueuedSale>> {
  return withDb(async (db) => {
    const raw = await readQueuedSaleRecord(db, queueRecordId);

    if (!raw.ok) return { ok: false, reason: "storage_unavailable" };
    if (raw.value === null) return { ok: false, reason: "not_found" };

    const parsed = readQueuedSale(raw.value);

    if (!parsed.ok) return { ok: false, reason: "corrupt_record" };

    const marked = markQueuedSaleAttempt(parsed.record, now);
    const written = await putQueuedSale(db, marked);

    return written.ok ? { ok: true, value: marked } : { ok: false, reason: "write_failed" };
  });
}

/**
 * Removes ONE synced record.
 *
 * Guarded on state deliberately: only a sale the server has confirmed may be
 * removed from this device. Anything else is still the only copy of money that
 * changed hands, and deleting it would be the worst bug this feature could
 * ship. There is no bulk delete and no "clear queue" anywhere in this module.
 */
export async function deleteSyncedSale(queueRecordId: string): Promise<QueueResult<void>> {
  return withDb(async (db) => {
    const raw = await readQueuedSaleRecord(db, queueRecordId);

    if (!raw.ok) return { ok: false, reason: "storage_unavailable" };
    if (raw.value === null) return { ok: false, reason: "not_found" };

    const parsed = readQueuedSale(raw.value);

    if (!parsed.ok) return { ok: false, reason: "corrupt_record" };
    if (parsed.record.state !== "synced") return { ok: false, reason: "illegal_transition" };

    const deleted = await deleteQueuedSaleRecord(db, queueRecordId);

    return deleted.ok ? { ok: true, value: undefined } : { ok: false, reason: "write_failed" };
  });
}

// ---------------------------------------------------------------------------
// Startup recovery
// ---------------------------------------------------------------------------

export type QueueRecoveryReport = {
  recovered: number;
  quarantined: number;
  summary: QueueSummary;
};

/**
 * Returns any record stranded in `syncing` to `pending`.
 *
 * Runs at queue initialization. A process that dies mid-submission leaves a
 * record claiming to be in flight with nothing flying it; without this it would
 * sit there forever, invisible to a work list that only reads `pending`.
 *
 * Safe because of server-side idempotency, not because of optimism: the
 * interrupted submission carried this record's saleRequestId, and
 * complete_sale_v4 resolves that key before allocating an order number,
 * mutating inventory or writing an audit row. Retrying therefore either creates
 * the sale or returns the one already created. See recoverInterruptedSale.
 */
export async function recoverInterruptedSyncs(now: string): Promise<QueueResult<QueueRecoveryReport>> {
  const listing = await listQueuedSales();

  if (!listing.ok) return listing;

  const stranded = listing.value.sales.filter((sale) => sale.state === "syncing");

  if (stranded.length === 0) {
    return {
      ok: true,
      value: {
        recovered: 0,
        quarantined: listing.value.quarantined.length,
        summary: summarizeQueue(listing.value.sales),
      },
    };
  }

  const written = await withDb(async (db) => {
    for (const sale of stranded) {
      const result = await putQueuedSale(db, recoverInterruptedSale(sale, now));

      if (!result.ok) return { ok: false as const, reason: "write_failed" as const };
    }

    return { ok: true as const, value: undefined };
  });

  if (!written.ok) return written;

  const after = await listQueuedSales();

  return after.ok
    ? {
        ok: true,
        value: {
          recovered: stranded.length,
          quarantined: after.value.quarantined.length,
          summary: summarizeQueue(after.value.sales),
        },
      }
    : after;
}
